version: "3.8"

services:
  # --- 1. Banco de Dados PostgreSQL ---
  postgres-db:
    image: postgres:16-alpine # Usamos 16-alpine (leve)
    container_name: clinica_postgres_db
    environment:
      POSTGRES_USER: admin # Usuário do banco
      POSTGRES_PASSWORD: admin123 # Senha do banco
      POSTGRES_DB: clinica_db # Nome do banco de dados
    ports:
      - "5432:5432" # Expõe a porta 5432 para o seu computador local
    volumes:
      - postgres_data:/var/lib/postgresql/data # Garante que os dados persistam
    networks:
      - clinica-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d clinica_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  # --- 2. Prometheus (Coletor de Métricas) ---
  prometheus:
    image: prom/prometheus:latest
    container_name: clinica_prometheus
    ports:
      - "9090:9090" # Porta da interface do Prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml # Arquivo de configuração
    networks:
      - clinica-network
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"

  # --- 3. Grafana (Dashboard de Métricas) ---
  grafana:
    image: grafana/grafana:latest
    container_name: clinica_grafana
    ports:
      - "3001:3000" # Expõe Grafana na porta 3001 (para não conflitar com o Nest)
    depends_on:
      - prometheus
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin123
    networks:
      - clinica-network

# --- Volumes e Redes ---
volumes:
  postgres_data: # Define o volume para persistência do banco

networks:
  clinica-network: # Rede privada para os contêineres se comunicarem
    driver: bridge
